### ISSUE TITLE
testIterator test from QueueFileTest file is not passing ?

### ISSUE THREAD

**Issue by asztejnb** [square/tape#177] opened 2017-11-27 13:42 UTC
I downloaded the code a week ago and I was wondering if someone else has seeing testIterator test fail on every run.

// Expected behavior
The loop should cycle 2 times leaving variable saw with a value of 2

// Actual behavior
Variable saw has a value of 3 when 2 is expected
java.lang.AssertionError: Not true that <3> is equal to <2>

**Comment by JakeWharton** [comment] 2017-11-30 16:11
It passes on CI consistently. Can you debug more into the cause?

**Comment by chrissmith-mcafee** [comment] 2017-12-08 17:44
This appears to be due to being run on Windows. This particular test will attempt to delete the file, but it has not been closed and will fail (has been fixed in PR #181)

**Closed** 2017-12-08 17:48 UTC
